### ISSUE TITLE
Instructions on how to start

### ISSUE THREAD

**Issue by ThrashAbaddon** [Olodus/OpenDriveOnlineEditor#1]
I was wondering how can I start this project, I would like to play around a bit?

**Comment by Olodus** [comment]
Sorry for the late answer. 
This was side project I started while working with the OpenDrive format at work. It was not finished and as I'm no longer working at the same place I cannot tell you if I'll ever go back and get it into a more finished state. The truth is I had kinda forgot that I put this up as a public repo. You are free to fork and continue the work if you want to (there really should exist an open source tool that can show atleast a simplified version of a xodr file). If I remember correctly I got it so it parsed the format somewhat competently but stopped before getting it to paint the 2d representation correctly. Just run elm reactor in the directory and any browser pointed to localhost should hopefully let you chose a xodr file. 
Sorry again :)

**Comment by ThrashAbaddon** [comment]
Ah I see, ok then I'll try running it with elm reactor. Thank you for your explanation. :)
